# Generated by Django 5.1.4 on 2025-01-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
